variables:
  NET_VERSION: '6.0.x'
  PathToSolution: 'GitTrends.sln'
  PathToAzureFunctionsCsproj: 'GitTrends.Functions/GitTrends.Functions.csproj'
  PathToAndroidAppCsproj: 'GitTrends.Android/GitTrends.Android.csproj'
  PathToiOSAppCsproj: 'GitTrends.iOS/GitTrends.iOS.csproj'
  PathToUnitTestsCsproj: 'GitTrends.UnitTests/GitTrends.UnitTests.csproj'
  PathToUITestsCsproj: 'GitTrends.UITests/GitTrends.UITests.csproj'
  XcodeVersion: '13.3.1'

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'
  paths:
    exclude:
    - README.md

pr:
  autoCancel: 'true'
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

jobs:
  - job: Build_AzureFunctions
    displayName: Build Azure Functions
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: VSBuild@1
        displayName: 'Build Azure Functions'
        inputs:
          solution: '$(PathToAzureFunctionsCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

  - job: Build_UITests
    displayName: Build UI Tests
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: VSBuild@1
        displayName: 'Build UI Tests'
        inputs:
          solution: '$(PathToUITestsCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

  - job: Build_iOS_App
    displayName: Build iOS App
    pool: 
      vmImage: macos-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: XamariniOS@2
        inputs:
          solutionFile: '$(PathToiOSCsproj)'
          configuration: 'Release'
          packageApp: false
          buildForSimulator: true
          runNugetRestore: true

  - job: Build_Android_App
    displayName: Build Android App
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: VSBuild@1
        displayName: 'Build Android App'
        inputs:
          solution: '$(PathToAndroidCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

      - task: XamarinAndroid@1
        inputs:
          projectFile: '$(PathToAndroidCsproj)'
          msbuildVersionOption: 'latest'
          msbuildArchitectureOption: 'x64'
          jdkOption: 'JDKVersion'

  - job: Build_UnitTests
    displayName: Build Unit Tests
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: VSBuild@1
        displayName: 'Build Unit Tests'
        inputs:
          solution: '$(PathToUnitTestsCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

  - job: Run_UnitTests
    displayName: Run Unit Tests
    dependsOn: [Build_UnitTests, Build_Android_App, Build_iOS_App, Build_UITests]
    pool: 
      vmImage: windows-latest

    steps:      
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '$(NET_VERSION)'

      - task: CmdLine@2
        displayName: 'Run Unit Tests'
        inputs:
          script: |
            GetTestTokenApiKey: $(GETTESTTOKENAPIKEY)
            GetAppCenterApiKeysKey: $(GETAPPCENTERAPIKEYSKEY)
            GetSyncFusionInformationApiKey: $(GETSYNCFUSIONINFORMATIONAPIKEY)
            GetNotificationHubInformationApiKey: $(GETNOTIFICATIONHUBINFORMATIONAPIKEY)
            APPCENTER_SOURCE_DIRECTORY: .


            chmod -R 777 ./GitTrends.Android/appcenter-pre-build.sh
            ./GitTrends.Android/appcenter-pre-build.sh

      - task: VSBuild@1
        displayName: 'Run Unit Tests'
        inputs:
          solution: '$(PathToUnitTestsCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore -t:test'